### ISSUE TITLE
Connections.fromEKSPodIdentiy | ServiceAccount

### ISSUE THREAD

**Issue by moshloop** [flanksource/duty#1304]
```yaml
connections:
   fromEksPodIdentity: true
   fromServiceAccount: true
```

for EKS map all ENV values starting with AWS_
+ mount file specified in AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE
