### ISSUE TITLE
Unable to attach Team to a Component/Topology in Teams Spec

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/duty#178]
I am getting the following error:

```json
{
    "code": "23505",
    "details": "Key (name, properties)=(team.update, {\"team_id\": \"01889ef8-1f09-d790-841d-e5c0b6f40ee9\"}) already exists.",
    "hint": null,
    "message": "duplicate key value violates unique constraint \"event_queue_name_properties\""
}
````

Spec Data:

```yaml
components:
  - name: mission-control
    namespace: mission-control
    selector: app=mission-control
```
