### ISSUE TITLE
valueFrom.helmRef

### ISSUE THREAD

**Issue by moshloop** [flanksource/duty#305]
i.e. 

```
username: 
   valueFrom:
        helmRef:
           name: helm release name
           key: some.values.key

```

The helm values can be retrieved by looking for secrets called `sh.helm.release.v1.{name}.v{\d}` of type `helm.sh/release.v1` - then to extract the values 

Merge these 
k view-secret sh.helm.release.v1.{name}.v54 release | base64 -D | gzip -d | jq -r '.config'
into the defaults:
k view-secret sh.helm.release.v1.{name}.v54 release | base64 -D | gzip -d | jq -r '.chart.values'
