### ISSUE TITLE
When saving specs to the DB strip out empty objects

### ISSUE THREAD

**Issue by moshloop** [flanksource/duty#331]
e.g. instead. of

```yaml
exec:
  - script: echo 1
     test: {}
    display:
      expr: results
    checkout:
      password: {}
      username: {}
      connection: connection://git/robot-tests
      certificate: {}
    transform: {}
    connections: {}
```

```yaml
exec:
  - script: echo 1
    display:
      expr: results
    checkout:
      connection: connection://git/robot-tests
```
