### ISSUE TITLE
Config graph - Return all related_ids

### ISSUE THREAD

**Issue by moshloop** [flanksource/duty#812]
Currently only a single related id is returned, we should be returning a list e.g.

```yaml:
related:
   - id: abc
      type: soft|hard
```
