### ISSUE TITLE
Custom config views

### ISSUE THREAD

**Issue by moshloop** [flanksource/duty#85]
Dynamically generate views based on definitions in a basescraper

- If there is a another view with same id, but different name/tags - return an error at the end of the scrape run
- Sync the views to a config_views table and when updated generate/replace the view.

e.g. 

```yaml
views: 
- id: aws
   name: AWS
   filter: external_type LIKE 'AWS::%'
   columns:
      -  id: Account
         tag: account'
      -  id: Zone
         tag: zone
```

Thie above would generate the following view:
```sql
CREATE OR REPLACE VIEW configs_aws AS
    SELECT * , json_delete(tags, 'zone', 'account) as tags tags->>'zone' AS Zone,  tags->>'account' AS Account
    FROM configs
    WHERE external_type LIKE 'AWS::%';
```
