### ISSUE TITLE
SQL connections - Set username/password on the db connector

### ISSUE THREAD

**Issue by moshloop** [flanksource/duty#994]
i.e. Allow specifying a bare url without templating
```
sql:
   url: postgres://localhost/db
   username: ..
   password: ...

```
